/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsNewRouteImport } from './routes/investigations.new'
import { Route as InvestigationsIdRouteImport } from './routes/investigations.$id'

const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsNewRoute = InvestigationsNewRouteImport.update({
  id: '/investigations/new',
  path: '/investigations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsIdRoute = InvestigationsIdRouteImport.update({
  id: '/investigations/$id',
  path: '/investigations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations': typeof InvestigationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/graph': typeof GraphRoute
  '/investigations/$id': typeof InvestigationsIdRoute
  '/investigations/new': typeof InvestigationsNewRoute
  '/investigations/': typeof InvestigationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/graph'
    | '/investigations/$id'
    | '/investigations/new'
    | '/investigations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/graph'
    | '/investigations/$id'
    | '/investigations/new'
    | '/investigations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/graph'
    | '/investigations/$id'
    | '/investigations/new'
    | '/investigations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GraphRoute: typeof GraphRoute
  InvestigationsIdRoute: typeof InvestigationsIdRoute
  InvestigationsNewRoute: typeof InvestigationsNewRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/new': {
      id: '/investigations/new'
      path: '/investigations/new'
      fullPath: '/investigations/new'
      preLoaderRoute: typeof InvestigationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations/$id': {
      id: '/investigations/$id'
      path: '/investigations/$id'
      fullPath: '/investigations/$id'
      preLoaderRoute: typeof InvestigationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GraphRoute: GraphRoute,
  InvestigationsIdRoute: InvestigationsIdRoute,
  InvestigationsNewRoute: InvestigationsNewRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
